version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=eshop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "5050:80" # Frontend (client)
      - "8080:8080" # Backend (api)
  api:
    build:
      dockerfile: Dockerfile.dev
      context: './backend'
    volumes:
    - /app/node_modules
    - ./backend:/app
    environment:
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=eshop
    depends_on:
      postgres:
       condition: service_healthy
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
